refactor(bootstrap): detect protoc from PATH only if PROTOC is undefined
PROTOC can now be defined as a environment value to the script.

Additionally, check that PROTOC:
- file exists
- execute permission is granted

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -42,9 +42,15 @@ shopt -s globstar
 
 # Protobuffer compiler
 #
-PROTOC=`which protoc`
 [ -z "$PROTOC" ] && {
-    echo "protoc: command not found"
+    PROTOC=`which protoc`
+    [ -z "$PROTOC" ] && {
+        echo "protoc: command not found"
+        exit 1
+    }
+}
+[ -x "$PROTOC" ] || {
+    echo "$PROTOC: file does not exist or execute permission is not granted"
     exit 1
 }
 
