refactor(bootstrap): rewrite help() as __help()

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -16,6 +16,37 @@
 set -e  # exit immediate if a command exists with a non-zero status
 shopt -s globstar  # enable bash globstar for recursive search
 
+__help()
+{
+    [ -n "$1" ] && >&2 echo "error: $1"
+    cat <<EOF
+
+Usage: ${0##*/} [-p <protodir>] [-l <langid>] [-d <destdir>]
+
+Where
+
+  <protodir> the location of the .proto files to be compiled. This is
+  the **root** dir.
+
+  <langid> language binding identifier (e.g. "go" or "python").
+
+    - The identifier value must be supported by protoc(1). ${0##*/}
+      does **not** validate the language ID value.
+
+    - If the value is "c", the script will use protoc-c(1) instead
+      of protoc(1). Make sure it is installed and found in PATH.
+
+    - If the value is "go", ${0##*/} appends ~/go/bin to PATH.
+
+  <destdir> write the compiled protobuf messages to this directory.
+
+Example
+
+  $ bootstrap -p protofiles/ -l python -d proto/gen
+    # Compile protobuf declarations for Python to ./proto/gen
+EOF
+    return 1
+}
 
 # Protobuffer compiler
 #
@@ -43,33 +74,6 @@ PROTODIR=
 #
 LANGID=
 
-help()
-{
-    cat <<EOF
-Usage: ${0##*/} [-p <protodir>] [-l <langid>] [-d <destdir>]
-
-Notes
-    - Make sure you have installed protobuf-compiler (protoc) and/or
-      protobuf-c-compiler (protoc-c) if you intend to produce c
-      bindings
-
-    - Make sure the compilers can be found in your path
-
-Where
-    <protodir> path to the _root_ dir containing the .proto files to
-        compile
-
-    <langid> language binding identifier (e.g. "go" or "python"). The
-        identifier must be understood by protoc(1); note that if the
-        identifier is "c", the script will use protoc-c(1), instead of
-        protoc(1).
-
-    <destdir> is the destination dir for the compiled protobuf messages
-
-EOF
-    [ -n "$1" ] && echo "error: $1"
-    exit 1
-}
 
 compile_files()
 {
@@ -82,20 +86,20 @@ compile_files()
     exit 0
 }
 
-while getopts "?hd:p:l:" o; do
+while getopts "hd:p:l:" o; do
 case "$o" in
     p) PROTODIR=$OPTARG ;;
     d) DESTDIR=$OPTARG ;;
     l) LANGID=$OPTARG ;;
-    h|?) help ;;
+    h) __help ;;
 esac
 done
 
 shift $((OPTIND-1)) # Shift off the options and optional --
 
-[ -z "$PROTODIR" ] && help "-p <protodir> not specified"
-[ -z "$DESTDIR" ] && help "-d <destdir> not specified"
-[ -z "$LANGID" ] && help "-l <langid> not specified"
+[ -z "$PROTODIR" ] && __help "-p <protodir> not specified"
+[ -z "$DESTDIR" ] && __help "-d <destdir> not specified"
+[ -z "$LANGID" ] && __help "-l <langid> not specified"
 
 [ "$LANGID" = "c" ] && {
     PROTOC=`which protoc-c`
